services:
  - type: web
    name: tradex
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_GOOGLE_CLIENT_SECRET
        sync: false
      - key: VITE_PROVER_ENDPOINT
        value: "http://localhost:3000/api/prove"
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=()
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
